UI Tests
Oleksandr-Boiko/aqa-course-ui-api-boiko pull request #1
Opened 2023-06-04 17:39 UTC by Oleksandr-Boiko

Task 1 - 5

2023-06-09 07:44 UTC, myevlentiev requested changes

2023-06-09 07:44 UTC, myevlentiev commented on src/test/java/qa/projects/RozetkaTests.java
> +        MainPage.listOfGoods.shouldHave(CollectionCondition.sizeLessThan(countOfGoods)); // test fails because count of goods not changes
сбробуй додати любий інший фільтр, щоб тест проходив

2023-06-09 07:44 UTC, myevlentiev commented on src/test/java/qa/projects/RozetkaTests.java
> +        int height = MainPage.listOfGoods.get(0).getSize().getHeight();
треба задати очікуванний результат, так як зараз тест порівнює актуальний з актуальним завжди

2023-06-09 07:44 UTC, myevlentiev commented on src/test/java/qa/projects/RozetkaTests.java
> +        height = MainPage.listOfGoods.get(0).getSize().getHeight();
треба задати очікуванний результат, так як зараз тест порівнює актуальний з актуальним завжди

2023-06-09 07:44 UTC, myevlentiev commented on src/test/java/qa/projects/RozetkaTests.java
> +        Thread.sleep(5000);
sleep краще не використовувати, краще явно чекати те що треба, в данному випадку можно щось таке зробити
MainPage.bigTileButton.shouldHave(Attribute.cssClass("catalog-view__button_state_active"));

2023-06-09 07:44 UTC, myevlentiev commented on src/test/java/qa/projects/RozetkaTests.java
> +        Thread.sleep(5000);
краще явно чекати, зроби якесь явне очікування

2023-06-09 07:44 UTC, myevlentiev commented on src/test/java/qa/projects/RozetkaTests.java
> +        Thread.sleep(8000);
спробуй зробити якесь явне очікування

2023-06-09 07:44 UTC, myevlentiev commented on src/test/java/qa/projects/RozetkaTests.java
> +        Thread.sleep(8000);
спробуй зробити якесь явне очікування

2023-06-09 07:44 UTC, myevlentiev commented on src/test/java/qa/projects/RozetkaTests.java
> +        Assert.assertTrue(firstProductValue > secondProductValue);
можно ще додати параметр message для помилки в assert

2023-06-09 07:44 UTC, myevlentiev commented on src/test/java/qa/projects/RozetkaTests.java
> +        int firstProductValue = Integer.parseInt(MainPage.productPrice.get(0).getText().replaceAll(" ", "").replaceAll("₴", ""));
можно ще так тут зробити
int firstProductValue = Integer.parseInt(MainPage.productPrice.get(0).getText().replaceAll("[^0-9]", ""));

2023-06-09 07:55 UTC, myevlentiev requested changes

2023-06-09 07:55 UTC, myevlentiev commented on src/test/java/qa/projects/RozetkaTests.java
> +    @Test
методам додай description

2023-06-09 07:55 UTC, myevlentiev commented on src/test/java/qa/projects/RozetkaTests.java
> +    public void test1() {
сбробуй замінити назви методів під логіку тестів, наприклад щось типо такого
sortingByHighestPriceTest

2023-06-09 10:21 UTC, myevlentiev requested changes

2023-06-09 10:21 UTC, myevlentiev commented on src/main/java/pages/MainPage.java
> +        MainPage.searchButton.click();
це не принциво, але в кейсах треба press Enter

2023-06-12 15:48 UTC, Oleksandr-Boiko commented on src/test/java/qa/projects/RozetkaTests.java
> +        MainPage.listOfGoods.shouldHave(CollectionCondition.sizeLessThan(countOfGoods)); // test fails because count of goods not changes
Fixed

2023-06-12 16:07 UTC, Oleksandr-Boiko commented on src/test/java/qa/projects/RozetkaTests.java
> +        int height = MainPage.listOfGoods.get(0).getSize().getHeight();
fixed

2023-06-12 16:07 UTC, Oleksandr-Boiko commented on src/test/java/qa/projects/RozetkaTests.java
> +        height = MainPage.listOfGoods.get(0).getSize().getHeight();
fixed

2023-06-12 16:11 UTC, Oleksandr-Boiko commented on src/test/java/qa/projects/RozetkaTests.java
> +        Assert.assertTrue(firstProductValue > secondProductValue);
fixed

2023-06-12 16:14 UTC, Oleksandr-Boiko commented on src/test/java/qa/projects/RozetkaTests.java
> +        int firstProductValue = Integer.parseInt(MainPage.productPrice.get(0).getText().replaceAll(" ", "").replaceAll("₴", ""));
fixed, thanks

2023-06-12 16:22 UTC, Oleksandr-Boiko commented on src/test/java/qa/projects/RozetkaTests.java
> +    @Test
fixed

2023-06-12 16:25 UTC, Oleksandr-Boiko commented on src/main/java/pages/MainPage.java
> +        MainPage.searchButton.click();
fixed

2023-06-21 07:46 UTC, myevlentiev requested changes

2023-06-21 07:46 UTC, myevlentiev commented on src/test/java/qa/projects/RozetkaTests.java
> +        Assert.assertEquals(smallGoodsheight, MainPage.listOfGoods.get(0).getSize().getHeight(), "height not equals");
так як зараз написано, при запуску теста на різних оточеннях він може падати, щоб тест стабільно проходив, перед відкритям браузера, можно спробувати задати постійний розмір екрану
Configuration.browserSize = "1366x768"; - приклад

2023-06-21 07:46 UTC, myevlentiev commented on src/main/java/pages/MainPage.java
> +    public static void checkListOfGoodsLoaded() {
виглядає так що це метод не відноситься до MainPage
тут краще винести, створити ListingPage наприклад

2023-06-21 07:46 UTC, myevlentiev commented on src/test/java/qa/projects/RozetkaTests.java
> +    public void test5() throws InterruptedException {
throws InterruptedException - зайве

2023-06-21 07:46 UTC, myevlentiev commented on src/test/java/qa/projects/RozetkaTests.java
> +    public void test4() throws InterruptedException {
throws InterruptedException - зайве

2023-06-21 07:46 UTC, myevlentiev commented on src/main/java/pages/MainPage.java
> +    public static SelenideElement sorting = $("rz-sort.catalog-settings__sorting select");
виглядає так що цей елемент не відноситься до MainPage
тут краще винести, створити ListingPage наприклад, також передивись інші елементи

2023-06-21 09:38 UTC, Oleksandr-Boiko commented on src/test/java/qa/projects/RozetkaTests.java
> +        Assert.assertEquals(smallGoodsheight, MainPage.listOfGoods.get(0).getSize().getHeight(), "height not equals");
Згоден, виправив

2023-06-21 09:38 UTC, Oleksandr-Boiko commented on src/test/java/qa/projects/RozetkaTests.java
> +    public void test5() throws InterruptedException {
Прибрав

2023-06-21 09:39 UTC, Oleksandr-Boiko commented on src/test/java/qa/projects/RozetkaTests.java
> +    public void test4() throws InterruptedException {
Прибрав

2023-06-21 09:44 UTC, Oleksandr-Boiko commented on src/main/java/pages/MainPage.java
> +    public static SelenideElement sorting = $("rz-sort.catalog-settings__sorting select");
Виніс

2023-06-21 09:44 UTC, Oleksandr-Boiko commented on src/main/java/pages/MainPage.java
> +    public static void checkListOfGoodsLoaded() {
Виніс

2023-06-27 08:16 UTC, myevlentiev approved these changes

2023-06-27 08:17 UTC, merged